### ISSUE TITLE
您好，然后没了，只能接受消息

### ISSUE THREAD

**Issue by mcc1095319343** [bujijam/qqchatgpt#1]
您好，打开main和go-cqhttp然后没了，只能登上并接受消息，没有机器人功能，要怎么实现

**Comment by mcc1095319343** [comment]
是因为用了chatgpt api的v1版本不能用了么，v3好像没有config这个选项

**Comment by bujijam** [comment]
现改用V3了

**Comment by bujijam** [comment]
（此外：机器人目前只能用于群聊，单独私聊机器人是不会有反应的）
